[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","B","UP","SIM"]
ignore = ["E203","E266","E501"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
