name: ci

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
    env:
      # Secrets tilgjengelig for hele jobben
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
      # Små kvalitets-envs
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_COLOR: "1"
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Verify secrets present
        run: |
          test -n "${OPENAI_API_KEY}" || { echo "❌ Missing OPENAI_API_KEY"; exit 1; }
          test -n "${SERPER_API_KEY}" || { echo "❌ Missing SERPER_API_KEY"; exit 1; }
          echo "✅ All secrets are set"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then pip install .; fi
          pip install pre-commit

      # Kjør alle pre-commit hooks på hele repoet
      - name: Lint & static checks (pre-commit)
        run: pre-commit run --all-files

      - name: Run tests
        run: pytest -q
