name: secrets-check

on:
  # Kjør manuelt fra Actions-tabben
  workflow_dispatch:
    inputs:
      live_ping:
        description: "Kjør ekte (lett) API-kall mot OpenAI og Serper"
        type: boolean
        default: false
  # Valgfritt: ukentlig sanity check (kun format/tilstedeværelse)
  schedule:
    - cron: "0 6 * * 1"  # mandag 06:00 UTC

permissions:
  contents: read

jobs:
  sanity:
    name: Sanity (presence & format)
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Verify secrets present
        run: |
          test -n "${OPENAI_API_KEY}" || { echo "❌ Missing OPENAI_API_KEY"; exit 1; }
          test -n "${SERPER_API_KEY}" || { echo "❌ Missing SERPER_API_KEY"; exit 1; }
          echo "✅ Both secrets are set"

      - name: Verify basic format
        run: |
          case "${OPENAI_API_KEY}" in
            sk-*) echo "✅ OPENAI_API_KEY format looks OK" ;;
            *)    echo "⚠️  OPENAI_API_KEY does not start with 'sk-'" ;;
          esac
          # Serper har ikke et fast prefix – vi sjekker bare lengde > 20
          if [ ${#SERPER_API_KEY} -lt 20 ]; then
            echo "⚠️  SERPER_API_KEY looks short (check)"; fi
          echo "ℹ️  Format checks are heuristic only."

  live-ping:
    name: Optional Live Ping
    if: ${{ inputs.live_ping == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      - name: OpenAI ping (cheap)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<'PY'
          import os, sys
          from openai import OpenAI
          key = os.environ.get("OPENAI_API_KEY")
          if not key: 
              print("❌ OPENAI_API_KEY missing"); sys.exit(1)
          client = OpenAI(api_key=key)
          # Minimalt kall: 1 tokens respons
          resp = client.chat.completions.create(
              model="gpt-4o",
              messages=[{"role":"user","content":"ping"}],
              max_tokens=1,
              temperature=0
          )
          print("✅ OpenAI ping OK; id:", resp.id)
          PY

      - name: Serper ping (optional & tiny)
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: |
          python - <<'PY'
          import os, sys, json, requests
          key = os.environ.get("SERPER_API_KEY")
          if not key:
              print("❌ SERPER_API_KEY missing"); sys.exit(1)
          # Lite søk; dette kan telle mot kvote. Kjøres kun når live_ping=true.
          r = requests.post(
              "https://google.serper.dev/search",
              headers={"X-API-KEY": key, "Content-Type": "application/json"},
              data=json.dumps({"q": "ping", "num": 1})
          )
          if r.status_code == 200:
              print("✅ Serper ping OK")
          else:
              print(f"❌ Serper ping failed: {r.status_code} - {r.text}"); sys.exit(1)
          PY
